/**
 * @fileoverview List of SuiteScript modules
 * @author Adam Davies
 */

'use strict';

module.exports = [
  'N/action',
  'N/auth',
  'N/cache',
  'N/certificateControl',
  'N/commerce/recordView',
  'N/compress',
  'N/config',
  'N/crypto',
  'N/crypto/certificate',
  'N/crypto/random',
  'N/currency',
  'N/currentRecord',
  'N/dataset',
  'N/datasetLink',
  'N/email',
  'N/encode',
  'N/error',
  'N/file',
  'N/format',
  'N/format/i18n',
  'N/http',
  'N/https',
  'N/https/clientCertificate',
  'N/keyControl',
  'N/log',
  'N/piremoval',
  'N/plugin',
  'N/portlet',
  'N/query',
  'N/recordContext',
  'N/record',
  'N/recordContext',
  'N/redirect',
  'N/render',
  'N/runtime',
  'N/search',
  'N/sftp',
  'N/sso',
  'N/suiteAppInfo',
  'N/task',
  'N/task/accounting/recognition',
  'N/transaction',
  'N/translation',
  'N/ui/dialog',
  'N/ui/message',
  'N/ui/serverWidget',
  'N/url',
  'N/util',
  'N/workbook',
  'N/workflow',
  'N/xml',
];
