name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Check linting and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn
          yarn prettier . --debug-check
      - run: |
          yarn lint

  test:
    name: Test rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          yarn
          yarn test
